<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net48</TargetFramework><LangVersion>latest</LangVersion><AssemblyName>Scp181DamageProbe</AssemblyName><Game>C:\Program Files (x86)\Steam\steamapps\common\SCP Secret Laboratory Dedicated Server\SCPSL_Data\Managed</Game></PropertyGroup><ItemGroup><Reference Include="Assembly-CSharp" HintPath="$(Game)\Assembly-CSharp.dll"/><Reference Include="LabApi" HintPath="$(Game)\LabApi.dll"/><Reference Include="CommandSystem.Core" HintPath="$(Game)\CommandSystem.Core.dll"/><Reference Include="UnityEngine.CoreModule" HintPath="$(Game)\UnityEngine.CoreModule.dll"/><Reference Include="Mirror" HintPath="$(Game)\Mirror.dll"/></ItemGroup></Project>